# Generated by Django 5.1.7 on 2025-03-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpenditureItem",
            fields=[
                (
                    "trans_id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Trans Id",
                    ),
                ),
                ("project", models.CharField(max_length=7, verbose_name="Project")),
                ("task", models.CharField(max_length=5, verbose_name="Task")),
                (
                    "expnd_type",
                    models.CharField(max_length=55, verbose_name="Expnd Type"),
                ),
                ("item_date", models.DateField(verbose_name="Item Date")),
                (
                    "employee_supplier",
                    models.CharField(max_length=255, verbose_name="Employee/Supplier"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Quantity"
                    ),
                ),
                ("uom", models.CharField(max_length=55, verbose_name="UOM")),
                (
                    "proj_func_burdened_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Proj Func Burdened Cost",
                    ),
                ),
                (
                    "project_burdened_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Project Burdened Cost",
                    ),
                ),
                (
                    "accrued_revenue",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Accrued Revenue"
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Bill Amount"
                    ),
                ),
                (
                    "comment",
                    models.CharField(max_length=255, null=True, verbose_name="Comment"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "oracle_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="Oracle ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
    ]
